### ISSUE TITLE
Settle on a license and add a LICENSE file to repo

### ISSUE THREAD

**Issue by jalperin** [pkp/xmlps#13]
need to figure out an appropriate license that we can use, given the dependencies we use in the. See the [beginnings of a discussion on the subject](https://github.com/pkp/xmlps/issues/11#issuecomment-126163507).

**Comment by axfelix** [comment]
I'm inclined to go with Apache over BSD/MIT because recent versions have been expressly declared compatible with GPLv3 (http://www.apache.org/licenses/GPL-compatibility.html) but it also explicitly facilitates patenting in a way that's likely to make our funding sources happy; as I stated in the other thread, I don't think we can get away with GPL here due to funder wishes and our liberal mixing of various other licenses in different stack modules (even if we don't redistribute them directly).

@asmecher, you okay with this? @crism, any particular thoughts?

**Comment by axfelix** [comment]
Eclipse and Mozilla are also theoretically nice GPL compromises but I'm afraid they muddy the waters too much and that most developers don't immediately recognize them.

**Comment by asmecher** [comment]
Have we really gotten this far without choosing a license?!

We had a recent discussion on the technical committee about GPL and the incompatibility between its "redistribute" clause and web software in general. The GPL Affero license came up as an option: http://www.gnu.org/licenses/gpl-faq.html#SeparateAffero

I don't have a strong preference; obviously compatibility is a big concern, so it might be good to list out your dependencies, particularly the ones you've modified, along with their licenses. If you use a tool like Composer to assemble your dependencies into a production environment, I don't believe you'll have to worry about license compatibility in quite the same way as you'd need to if you bundled everything into the package for distribution.

**Comment by axfelix** [comment]
Good idea. Modules:

LibreOffice -- Mozilla.
meTypeset -- GPL.
bibutils -- GPL.
ParsCit -- GPL.
Pandoc -- GPL.
wkhtmltopdf -- GPL.
Exiftool -- GPL.

We contribute directly to meTypeset, and we'd modified ParsCit at one point, but I think we're back to using the upstream version of everything.

hmmmmmmmmmmmmmmmmmmmmm.

**Comment by axfelix** [comment]
Planned modules, btw:

Cermine: Affero GPL.
jats2epub: GPL.

This is actually a surprise to me... if we swapped out LibreOffice for Abiword's CLI converter (which is known to produce slightly less faithful Word image positioning and whatnot, but seeing as we're only using it for non-native docx uploads to provide input to meTypeset it may not matter), we could actually have a fully GPL stack.

**Comment by asmecher** [comment]
I used Abiword years ago and it's probably come a long way, but always found it to be a very, very junior cousin to LibreOffice & co. Given that probably most users will be depending on .docx conversion, I think LibreOffice is clear leader.

**Comment by axfelix** [comment]
I have the same impression of Abiword but was talking to Artefactual recently about their office document normalization routes and they found CLI use of LibreOffice to be such a god-awful bear due to the jvm stuff that they preferred Abiword's slightly inferior formatting when it was only being used as a middleman, as it would be here.

**Comment by axfelix** [comment]
The Java stuff hasn't been a huge problem in our stack so far because we wrapped it better (I think their whole Gearman/Django setup made things particularly difficult on that end), but I did a similar thing in a different project recently where I elected to go with Gnumeric's CLI ssconvert instead of LibreOffice for Excel->CSV conversion because it was lighter-weight, so it's not unprecedented...

**Comment by axfelix** [comment]
KM confirmed they don't have any problems with GPLing the stack, btw (or rather, I gave them several opportunities to object and they didn't), so it's officially done in https://github.com/pkp/xmlps/commit/6400595cbd95d2b409af970d08a79e594676fb37. Yeehaw.
