### ISSUE TITLE
6283-16863-1-CE.docx hangs meTypeset indefinitely

### ISSUE THREAD

**Issue by axfelix** [pkp/xmlps#44]
We may need to handle this by putting a timeout on some of the individual queue processors (also, this may have been causing more problems than I realized up to now, @jnicolls @crism) -- I've never seen a document reliably hang meTypeset indefinitely before, but this one definitely does; just reproduced locally.

[6283-16863-1-CE.docx](https://github.com/pkp/xmlps/files/49232/6283-16863-1-CE.docx)

**Comment by MartinPaulEve** [comment]
Thanks, Alex. Interesting.

Bug is in the reference linker module since passing --nolink to the command line completes succesfully.

Have a suspicion that this regex is to blame:

new_text = re.sub(regex, u'({0}\g<text>{1})'.format(xref_before, xref_after), in_string, 1)

Will investigate when I have time, but this is confirmed.

**Comment by MartinPaulEve** [comment]
P.S. what's the license on this document? If it's available to re-use I can write a test case very quickly.

**Comment by axfelix** [comment]
Openly reusable. We did manage to sort that part out with the corpus this round :)

**Comment by MartinPaulEve** [comment]
Ok, will put this on my list.

Need to trace where reflinker is dying. Might then be able to isolate
subset of document causing the bug.

**Comment by MartinPaulEve** [comment]
[bug.docx](https://github.com/pkp/xmlps/files/53236/bug.docx)
Have isolated this to the attached minimal test document.

Have confirmed that bug exists in this line:

new_text = re.sub(regex, u'({0}\g<text>{1})'.format(xref_before, xref_after), in_string, 1)

of the reference linker. Occurs when:

```html
regex = \((?P<text>.*?[^(xref)]*?[^(xref)]*?[^(xref)]*?[^(xref)]*?[^(xref)]*?[^(xref)]*?[^(xref)]*?[^(xref)]*?[^(xref)]*?[^(xref)]*?)\)

in_string = <p>This is a test (10.7% vs. 8.4%, <italic>&#935;</italic>2= 1.3, <italic>df</italic>=1, <italic>p</italic>=0.3), erosions (10.9% vs. 12.2%, <italic>&#935;</italic>2= 64.5, <italic>df</italic>=1, <italic>p</italic>=0.5), that triggers an infinite hang (5.9% vs. 6.3%, <italic>&#935;</italic>2= 0.05, <italic>df</italic>=1, <italic>p</italic>=0.8).</p>

format replace string = (<xref ref-type="bibr" id="IDd906aed4-e7c2-4e2f-a74f-7a09ef6390da" rid="TO_LINK">\g<text></xref>)
\```

**Comment by MartinPaulEve** [comment]
Further diagnosis and suggested fixes:

Diagnosis: This occurs because the dynamically generated regex is complex and possibly infinitely recursive. The python regex engine is crashing.

Fixes (two components):

Exclude any value that includes a percentage sign from the reference linker. This will eliminate further false positive matches when the user is typing equations in brackets and so is worth doing anyway. It is not a general fix for this problem though.

The more generalisable fix is to replace the previously hideous regex construction routine with a negative word lookahead for xref.

These fixes are both implemented and test cases committed in https://github.com/MartinPaulEve/meTypeset/commit/4fb31ae25d387e1b05c683347760124449f24979. This passes all existing regression tests.

**Comment by axfelix** [comment]
Thanks! Closing, moving that document out of testing jail, and pulling meTypeset on the server.
